### ISSUE TITLE
Yarn 3 has trouble resolving react-native-reanimated

### ISSUE THREAD

**Issue by riordanpawley** [nandorojo/solito#29]
Love the project <3

```txt
The project's Babel config is invalid: Cannot find module 'react-native-reanimated/plugin' from '/Users/riordan/prog/solito-example2/apps/next'
Error: Cannot find module 'react-native-reanimated/plugin' from '/Users/riordan/prog/solito-example2/apps/next'
```

Easy enough fix but wasn't sure how to go about documenting it so I'm just gonna make an issue.
I'm also not 100% positive its not some configuration issue on my end. I tried to find other ways to fix it and came up short though.

The FIX:
I ran yarn set version classic and created this .yarnrc.yml

[project-root]/.yarnrc.yml
```yaml
nmMode: classic

nmSelfReferences: false

nodeLinker: node-modules

# this is probably different user to user# I think 'yarn set version classic' is supposed to fill this but i had to manually add it
yarnPath: .yarn/releases/yarn-1.23.0-20220130.1630.cjs
```
